codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 85%
        threshold: 1%
        if_ci_failed: error

flags:
  unittests:
    paths:
      - src/
    carryforward: true

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "docs/"
  - "examples/"
  - "*.md"
  - "setup.py"
