codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 70%
        threshold: 1%
        if_ci_failed: error

    patch:
      default:
        target: 85%
        threshold: 1%
        if_ci_failed: error

flags:
  unittests:
    paths:
      - src/
    carryforward: true

comment:
  layout: "header, diff, flags, files, footer"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "docs/"
  - "examples/"
  - "*.md"
  - "setup.py"

# Exclude patterns for lines with low testing value
# Note: These patterns work with coverage.py's exclude_lines configuration
# and should match patterns in pyproject.toml [tool.coverage.report]
parsers:
  python:
    # Skip import lines - low value to cover
    skip:
      - '^\\s*from .+ import .+$'
      - '^\\s*import .+$'
    # Skip type checking blocks
    skip_branches:
      - "if TYPE_CHECKING:"
