codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 74%
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 74%
        threshold: 2%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

ignore:
  - "tests/"
  - "docs/"
  - "examples/"
  - "*.md"
  - "setup.py"

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: unittests
      paths:
        - src/
      carryforward: true
