name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install and run Ruff
      uses: astral-sh/ruff-action@v3
      with:
        src: "./src"
        args: "check --output-format=github"
    - name: Run Ruff formatter
      uses: astral-sh/ruff-action@v3
      with:
        src: "./src"
        args: "format --check"
