name: publish to pypi

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: pip install hatch
      - name: Build artifacts
        run: hatch build
      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@v2.0.1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          print-hash: true
          skip-existing: true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
